Repository softeerbootcamp4th/Team7-HybridJGS-FE, pull requests merged in 2024-08, with the labels that each got.

#80 [Fix] Popup 제출 후 스크롤 방지 삭제
  client/src/hooks/usePopup.tsx
Labels: fix

#76 [Feat] 캐스퍼 커스텀 페이지 UI 구현
  client/package.json
  client/public/assets/casper-custom/battery-frame.svg
  client/public/assets/casper-custom/battery.svg
  client/public/assets/icons/arrow.svg
  client/src/constants/CasperCustom/customStep.tsx
  client/src/contexts/casperCustomContext.tsx
  client/src/dom-to-image.d.ts
  client/src/features/CasperCustom/Battery.tsx
  client/src/features/CasperCustom/CasperCardBackUI.tsx
  client/src/features/CasperCustom/CasperCardFrontUI.tsx
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/features/CasperCustom/CasperCustomPanel.tsx
  client/src/features/CasperCustom/CasperCustomProcess.tsx
  client/src/features/CasperCustom/MyCasperCardBack.tsx
  client/src/features/CasperCustom/MyCasperCardFront.tsx
  client/src/pages/CasperCustom/index.tsx
  client/src/utils/getCasperOptionDescription.ts
  client/src/utils/saveDomImage.ts
  client/yarn.lock
Labels: feat

#81 [Feat] 선착순 이벤트 페이지 UI 구현
  client/public/assets/rush/car.jpg
  client/public/assets/rush/casper/charge-1.png
  client/public/assets/rush/casper/charge-2.png
  client/public/assets/rush/casper/comfortable-1.png
  client/public/assets/rush/casper/comfortable-2.png
  client/public/assets/rush/casper/far-1.png
  client/public/assets/rush/casper/far-2.jpeg
  client/public/assets/rush/casper/fast-1.png
  client/public/assets/rush/casper/fast-2.png
  client/public/assets/rush/casper/smart-key.png
  client/public/assets/rush/casper/wide-1.png
  client/public/assets/rush/casper/wide-2.png
  client/public/assets/rush/electric/charge.jpg
  client/public/assets/rush/electric/e-csp.jpg
  client/public/assets/rush/electric/eco-friendly.jpg
  client/public/assets/rush/electric/pollution.jpg
  client/public/assets/rush/electric/ranc.jpg
  client/src/components/Notice/index.tsx
  client/src/constants/Rush/electricCardData.tsx
  client/src/features/Rush/Background.tsx
  client/src/features/Rush/BalanceGame.tsx
  client/src/features/Rush/CasperCharge.tsx
  client/src/features/Rush/CasperComfortable.tsx
  client/src/features/Rush/CasperDescription.tsx
  client/src/features/Rush/CasperFar.tsx
  client/src/features/Rush/CasperFast.tsx
  client/src/features/Rush/CasperSection.tsx
  client/src/features/Rush/CasperSmartKey.tsx
  client/src/features/Rush/CasperSubDescription.tsx
  client/src/features/Rush/CasperWide.tsx
  client/src/features/Rush/ElectricAdvantage.tsx
  client/src/features/Rush/ElectricReason.tsx
  client/src/features/Rush/ElectricReasonCard.tsx
  client/src/features/Rush/ElectricSection.tsx
  client/src/features/Rush/FAQ.tsx
  client/src/features/Rush/Intro.tsx
  client/src/features/Rush/ReasonFirst.tsx
  client/src/features/Rush/ReasonSecond.tsx
  client/src/features/Rush/ReasonSection.tsx
  client/src/pages/Lottery/index.tsx
  client/src/pages/Rush/index.tsx
Labels: feat

#83 [Fix] 배포 시 이미지 403 오류 수정
  client/src/constants/Main/lotteryEventData.ts
  client/src/features/Main/Rush.tsx
Labels: fix

#84 [Feat] 캐스퍼 showcase UI 구현
  client/src/constants/CasperCustom/casper.ts
  client/src/constants/CasperShowCase/showCase.ts
  client/src/features/CasperShowCase/CasperCards.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
  client/src/pages/CasperShowCase/index.tsx
Labels: feat

#88 [Fix] 툴팁 위치 오류 수정
  client/src/components/Tooltip/index.tsx
Labels: fix

#89 [Refactor] Flux 패턴 적용 및 리팩토링
  client/src/components/Layout/index.tsx
  client/src/components/PopUp/index.tsx
  client/src/constants/CasperCustom/casper.ts
  client/src/constants/CasperCustom/customStep.tsx
  client/src/contexts/casperCustomContext.tsx
  client/src/contexts/phoneNumberContext.tsx
  client/src/features/CasperCustom/CasperCardBackUI.tsx
  client/src/features/CasperCustom/CasperCardFrontUI.tsx
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/features/CasperCustom/CasperCustomPanel.tsx
  client/src/features/CasperCustom/CasperCustomProcess.tsx
  client/src/features/CasperCustom/EyesPanel.tsx
  client/src/features/CasperCustom/MyCasperCardBack.tsx
  client/src/features/CasperCustom/MyCasperCardFront.tsx
  client/src/hooks/useCasperCustomContext.ts
  client/src/hooks/useCasperCustomDispatchContext.ts
  client/src/hooks/useCasperCustomStateContext.ts
  client/src/hooks/usePhoneNumberDispatchContext.ts
  client/src/hooks/usePhoneNumberStateContext.ts
  client/src/hooks/usePopup.tsx
  client/src/pages/Lottery/index.tsx
  client/src/types/casperCustom.ts
  client/src/types/phoneNumber.ts
  client/src/utils/CasperCustom/getCasperEyesComponent.tsx
  client/src/utils/CasperCustom/getCasperMouthComponent.tsx
  client/src/utils/CasperCustom/getCasperOptionDescription.ts
Labels: refactor

#91 [Fix] context import type 수정
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
Labels: fix

#92 [Feat] 공통 애니메이션 정의
  client/src/constants/animation.ts
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CasperFlipCard.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
Labels: feat

#94 [Feat] 뱃지 화면 애니메이션 구현
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/features/CasperCustom/CasperCustomProcess.tsx
  client/src/pages/CasperCustom/index.tsx
  client/src/pages/CasperCustomResult/index.tsx
  client/src/pages/CasperShowCase/index.tsx
  client/src/router.tsx
Labels: feat

#97 [Fix] 캐스퍼 쇼케이스 화면 로딩 오래 걸리는 오류 수정
  client/src/features/CasperCustom/CasperFlipCard.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
  client/src/hooks/useLazyLoading.ts
Labels: fix

#105 [Feat] 스크롤 애니메이션 및 각 섹션 별 헤더 스타일 변경 기능 구현
  client/src/components/ButtonHeader/index.style.tsx
  client/src/components/Footer/index.tsx
  client/src/components/Header/index.stories.tsx
  client/src/components/Header/index.tsx
  client/src/components/Layout/index.tsx
  client/src/components/Notice/index.tsx
  client/src/constants/PageSections/sections.ts
  client/src/constants/animation.ts
  client/src/contexts/scrollHeaderStyleContext.tsx
  client/src/features/Lottery/CustomDesign.tsx
  client/src/features/Lottery/Description.tsx
  client/src/features/Lottery/HeadLamp.tsx
  client/src/features/Lottery/Headline.tsx
  client/src/features/Lottery/Intro.tsx
  client/src/features/Lottery/NewColor.tsx
  client/src/features/Lottery/PixelDesign.tsx
  client/src/features/Lottery/Section.tsx
  client/src/features/Lottery/ShortCut.tsx
  client/src/features/Lottery/SmileBadge.tsx
  client/src/features/Lottery/WheelDesign.tsx
  client/src/features/Main/Headline.tsx
  client/src/features/Main/LearnMore.tsx
  client/src/features/Main/Lottery.tsx
  client/src/features/Main/Rush.tsx
  client/src/features/Main/Section.tsx
  client/src/features/Rush/Background.tsx
  client/src/features/Rush/BalanceGame.tsx
  client/src/features/Rush/CasperCharge.tsx
  client/src/features/Rush/CasperComfortable.tsx
  client/src/features/Rush/CasperDescription.tsx
  client/src/features/Rush/CasperFar.tsx
  client/src/features/Rush/CasperFast.tsx
  client/src/features/Rush/CasperSection.tsx
  client/src/features/Rush/CasperSmartKey.tsx
  client/src/features/Rush/CasperSubDescription.tsx
  client/src/features/Rush/CasperWide.tsx
  client/src/features/Rush/ElectricAdvantage.tsx
  client/src/features/Rush/ElectricReason.tsx
  client/src/features/Rush/ElectricReasonCard.tsx
  client/src/features/Rush/ElectricSection.tsx
  client/src/features/Rush/FAQ.tsx
  client/src/features/Rush/Intro.tsx
  client/src/features/Rush/ReasonFirst.tsx
  client/src/features/Rush/ReasonSecond.tsx
  client/src/features/Rush/ReasonSection.tsx
  client/src/hooks/useHeaderStyleObserver.ts
  client/src/hooks/useScrollHeaderStyleContext.ts
  client/src/pages/Lottery/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Rush/index.tsx
  client/src/types/scrollHeaderStyle.ts
  client/src/types/sections.ts
Labels: feat

#111 [Feat] Popup Submit 작동 추가
  client/.gitignore
  client/src/components/CTAButton/index.tsx
  client/src/components/PopUp/index.tsx
Labels: feat

#101 [Feat] 어드민 공통 컴포넌트 구현
  admin/public/assets/icons/close.svg
  admin/src/components/Button/index.tsx
  admin/src/components/Dropdown/index.tsx
  admin/src/components/Header/index.tsx
  admin/src/components/Input/index.tsx
  admin/src/components/Modal/index.tsx
  admin/src/components/TabHeader/index.tsx
  admin/src/components/Table/index.tsx
  admin/src/hooks/useModal.tsx
  admin/src/index.css
  admin/src/pages/Login/index.tsx
  admin/src/router.tsx
Labels: feat

#104 [Feat] 어드민 UI 구현
  .github/workflows/admin_pull_request.yml
  .github/workflows/client_pull_request.yml
  admin/index.html
  admin/public/assets/icons/calendar.svg
  admin/public/assets/icons/down-arrow.svg
  admin/public/assets/icons/left-arrow.svg
  admin/src/assets/react.svg
  admin/src/components/Button/index.tsx
  admin/src/components/DatePicker/index.tsx
  admin/src/components/Dropdown/index.tsx
  admin/src/components/Layout/index.tsx
  admin/src/components/TabHeader/index.tsx
  admin/src/components/Table/index.tsx
  admin/src/components/TimePicker/index.tsx
  admin/src/constants/rush.ts
  admin/src/constants/tabOptions.ts
  admin/src/contexts/rushEventContext.tsx
  admin/src/features/Rush/ApplicantList.tsx
  admin/src/features/Rush/EventList.tsx
  admin/src/hooks/useRushEventDispatchContext.ts
  admin/src/hooks/useRushEventStateContext.ts
  admin/src/index.css
  admin/src/pages/Login/index.tsx
  admin/src/pages/Lottery/index.tsx
  admin/src/pages/LotteryWinner/index.tsx
  admin/src/pages/Rush/index.tsx
  admin/src/router.tsx
  admin/src/types/rush.ts
  admin/src/utils/getTimeDifference.ts
  admin/tailwind.config.js
Labels: feat

#119 [Feat] 캐스퍼 페이지 헤더 반영
  client/src/constants/PageSections/sections.ts
  client/src/pages/CasperCustom/index.tsx
  client/src/pages/CasperShowCase/index.tsx
  client/src/types/sections.ts
Labels: feat

#121 [Feat] 에러 핸들링 구현
  client/public/assets/icons/casper-error.svg
  client/src/apis/authAPI.ts
  client/src/apis/lotteryAPI.ts
  client/src/components/PopUp/index.tsx
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/hooks/useBlockNavigation.ts
  client/src/hooks/useFetch.ts
  client/src/hooks/usePopup.tsx
  client/src/pages/CasperCustom/index.tsx
  client/src/pages/CasperShowCase/index.tsx
  client/src/pages/ErrorBoundary/index.tsx
  client/src/pages/Lottery/index.tsx
  client/src/pages/NotFound/index.tsx
  client/src/router.tsx
  client/src/types/lotteryApi.ts
  client/src/utils/fetchWithTimeout.ts
Labels: feat

#128 [Fix] action 코멘트 조건 수정
  .github/workflows/admin_pull_request.yml
  .github/workflows/client_pull_request.yml
Labels: fix

#129 [Feat] 어드민 UI 구현
  admin/public/assets/icons/calendar.svg
  admin/src/apis/lotteryAPI.ts
  admin/src/apis/rushAPI.ts
  admin/src/components/Layout/index.tsx
  admin/src/components/Table/index.tsx
  admin/src/components/TextField/index.tsx
  admin/src/constants/lottery.ts
  admin/src/constants/rush.ts
  admin/src/contexts/rushEventContext.tsx
  admin/src/features/Rush/EventList.tsx
  admin/src/features/Rush/Layout.tsx
  admin/src/hooks/useInfiniteFetch.ts
  admin/src/pages/Lottery/index.tsx
  admin/src/pages/LotteryWinner/index.tsx
  admin/src/pages/LotteryWinnerList/index.tsx
  admin/src/pages/Rush/index.tsx
  admin/src/pages/RushPrizeForm/index.tsx
  admin/src/pages/RushSelectForm/index.tsx
  admin/src/pages/RushWinnerList/index.tsx
  admin/src/router.tsx
  admin/src/types/common.ts
  admin/src/types/lottery.ts
  admin/src/types/lotteryApi.ts
  admin/src/types/rush.ts
Labels: feat

#132 [Feat] 기존의 ErrorBoundary를 react-error-boundary으로 수정
  admin/yarn.lock
  client/package.json
  client/src/components/Layout/index.tsx
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/hooks/useFetch.ts
  client/src/pages/ErrorBoundary/index.tsx
  client/src/pages/ErrorElement/index.tsx
  client/src/pages/Lottery/index.tsx
  client/src/router.tsx
  client/yarn.lock
Labels: feat

#133 [Feat] 공유 링크 구현
  admin/.gitignore
  client/src/apis/linkAPI.ts
  client/src/constants/Auth/token.ts
  client/src/constants/cookie.ts
  client/src/features/CasperCustom/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/pages/Lottery/index.tsx
  client/src/types/linkApi.ts
  client/src/types/lotteryApi.ts
Labels: feat

#136 [Feat] 어드민 - Error handling 구현
  admin/package.json
  admin/src/components/Layout/index.tsx
  admin/src/components/Route/index.tsx
  admin/src/hooks/useFetch.ts
  admin/src/hooks/useInfiniteFetch.ts
  admin/src/pages/ErrorElement/index.tsx
  admin/src/pages/NotFound/index.tsx
  admin/src/router.tsx
  admin/yarn.lock
Labels: feat

#139 [Feat] 어드민 - API 연동
  admin/src/apis/lotteryAPI.ts
  admin/src/apis/rushAPI.ts
  admin/src/components/DatePicker/index.tsx
  admin/src/components/FileInput/index.tsx
  admin/src/components/TimePicker/index.tsx
  admin/src/components/Toast/index.tsx
  admin/src/constants/common.ts
  admin/src/constants/rush.ts
  admin/src/contexts/rushEventContext.tsx
  admin/src/features/Rush/EventList.tsx
  admin/src/features/Rush/RushPrizeForm.tsx
  admin/src/features/Rush/RushSelectForm.tsx
  admin/src/hooks/useFetch.ts
  admin/src/hooks/useInfiniteFetch.ts
  admin/src/hooks/useToast.tsx
  admin/src/pages/Lottery/index.tsx
  admin/src/pages/LotteryParticipantList/index.tsx
  admin/src/pages/LotteryWinner/index.tsx
  admin/src/pages/LotteryWinnerList/index.tsx
  admin/src/pages/Rush/index.tsx
  admin/src/pages/RushPrizeForm/index.tsx
  admin/src/pages/RushSelectForm/index.tsx
  admin/src/router.tsx
  admin/src/types/common.ts
  admin/src/types/lottery.ts
  admin/src/types/lotteryApi.ts
  admin/src/types/rush.ts
  admin/src/types/rushApi.ts
  admin/src/utils/getDateDifference.ts
Labels: feat

#141 [Fix] 메인 페이지 오류 수정
  client/src/constants/cookie.ts
  client/src/features/CasperCustom/CasperCustomForm.tsx
  client/src/hooks/useFetch.ts
  client/src/pages/ErrorElement/index.tsx
Labels: fix

#143 [Chore] og 태그 및 favicon 적용
  client/index.html
  client/package.json
  client/public/assets/favicon.ico
  client/public/assets/og-image.png
  client/yarn.lock
Labels: chore

#144 [Chore] 어드민 favicon 적용
  admin/index.html
  admin/public/assets/favicon.ico
  admin/public/vite.svg
Labels: chore

#147 [Feat] 어드민 API 예외처리
  admin/src/apis/authAPI.ts
  admin/src/hooks/useFetch.ts
  admin/src/pages/Login/index.tsx
  admin/src/utils/fetchWithTimeout.ts
  client/src/utils/fetchWithTimeout.ts
Labels: fix, feat

#150 [Fix] 공유 URL 수정
  client/src/features/CasperCustom/CasperCustomFinish.tsx
Labels: fix

#152 [Feat] 캐스퍼 봇 커스텀 UX/UI 개선
  client/src/constants/CasperCustom/casper.ts
  client/src/features/CasperCustom/CasperCustomFinishing.tsx
Labels: feat

#164 [Refactor] CasperCustom 폴더구조 변경
  client/src/constants/CasperCustom/customStep.tsx
  client/src/features/CasperCustom/CasperCard/CasperCardBackUI.tsx
  client/src/features/CasperCustom/CasperCard/CasperCardFrontUI.tsx
  client/src/features/CasperCustom/CasperCard/CasperFlipCard.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardBack.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardFront.tsx
  client/src/features/CasperCustom/CasperCustomPanel/CasperCustomPanel.tsx
  client/src/features/CasperCustom/CasperCustomPanel/CasperCustomPanelLayout.tsx
  client/src/features/CasperCustom/CasperCustomPanel/CustomOptionImageItem.tsx
  client/src/features/CasperCustom/CasperCustomPanel/EyesOptionImageItem.tsx
  client/src/features/CasperCustom/CasperCustomPanel/EyesPanel.tsx
  client/src/features/CasperCustom/CasperCustomPanel/SharedPanel.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomForm.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomProcess.tsx
  client/src/features/CasperCustom/index.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
Labels: chore, refactor

#168 [Fix] 전체적인 UI 오류 수정
  client/src/features/Main/Lottery.tsx
  client/src/features/RushGame/RushGameComponents/RushBar.tsx
  client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx
Labels: fix

#161 [Feat] UX 개선
  client/src/components/PopUp/index.tsx
  client/src/components/Scroll/index.tsx
  client/src/features/CasperCustom/CasperCard/CasperCardBackUI.tsx
  client/src/features/CasperCustom/CasperCard/CasperFlipCard.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinishing.tsx
  client/src/features/CasperShowCase/CasperCards.tsx
  client/src/features/CasperShowCase/TransitionCasperCardItem.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
  client/src/features/Lottery/Headline.tsx
  client/src/features/Lottery/Intro.tsx
  client/src/features/Main/Headline.tsx
  client/src/features/Main/Lottery.tsx
  client/src/features/Main/Section.tsx
  client/src/features/Rush/Common/Headline.tsx
  client/src/features/Rush/Common/Intro.tsx
  client/src/hooks/useScrollToTarget.ts
  client/src/pages/CasperShowCase/index.tsx
  client/src/pages/Lottery/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Rush/index.tsx
  client/src/types/casper.ts
Labels: feat

#169 [Feat] RushCard 색상 랜덤 기능 구현
  client/src/constants/Rush/rushCard.ts
  client/src/features/RushGame/RushGameComponents/RushCardComparison.tsx
  client/src/utils/getRandomCardColors.ts
Labels: feat

#171 [Feat] 선착순 밸런스 게임 이벤트 공유 링크 연동
  .github/workflows/client_push.yml
  client/src/pages/RushGame/index.tsx
Labels: feat

#173 [Chore] 카운트 다운 서버 시간으로 변경
  client/src/contexts/rushGameContext.tsx
Labels: chore

#175 [Refactor] LightHouse 성능 개선
  client/index.html
  client/public/assets/main/lottery/prize-1.png
  client/robots.txt
  client/src/components/LotteryEvent/index.tsx
  client/src/components/RushEvent/index.tsx
  client/src/index.css
Labels: refactor

#179 [Fix] 공유 링크 이미지 뜨게 수정
  client/index.html
Labels: fix

#177 [Fix] Transition 버벅임 문제 해결
  client/src/features/CasperShowCase/CasperCards.tsx
  client/src/features/CasperShowCase/TransitionCasperCardItem.tsx
  client/src/features/CasperShowCase/TransitionCasperCards.tsx
Labels: fix

#181 [Fix] 스티커랑 배경 색상이 겹치는 부분 예외처리 추가
  client/public/assets/casper-custom/sticker/charge-max.png
  client/public/assets/casper-custom/sticker/charge-max.svg
  client/public/assets/casper-custom/sticker/charge-none.png
  client/public/assets/casper-custom/sticker/charge-none.svg
  client/public/assets/casper-custom/sticker/electric.png
  client/public/assets/casper-custom/sticker/electric.svg
  client/public/assets/casper-custom/sticker/lovely.png
  client/public/assets/casper-custom/sticker/lovely.svg
  client/public/assets/casper-custom/sticker/twinkle.png
  client/public/assets/casper-custom/sticker/twinkle.svg
  client/src/constants/CasperCustom/casper.ts
  client/src/features/CasperCustom/CasperCard/CasperCardFrontUI.tsx
  client/src/types/casperCustom.ts
  client/src/utils/CasperCustom/getCasperEyesComponent.tsx
  client/src/utils/CasperCustom/getCasperMouthComponent.tsx
  client/src/utils/CasperCustom/getCasperStickerComponent.tsx
Labels: fix

#186 [Feat] LightHouse 성능 개선
  client/index.html
  client/public/assets/main/lottery/prize-1.png
  client/public/assets/main/lottery/prize-2.png
  client/public/assets/main/lottery/prize-3.png
  client/public/assets/main/lottery/prize-4.png
  client/public/assets/main/lottery/prize-5.png
  client/public/robots.txt
  client/src/features/Lottery/CustomDesign.tsx
  client/src/features/Lottery/HeadLamp.tsx
  client/src/features/Lottery/Intro.tsx
  client/src/features/Lottery/NewColor.tsx
  client/src/features/Lottery/PixelDesign.tsx
  client/src/features/Lottery/Section.tsx
  client/src/features/Lottery/ShortCut.tsx
  client/src/features/Lottery/SmileBadge.tsx
  client/src/features/Lottery/WheelDesign.tsx
  client/src/features/Main/LearnMore.tsx
  client/src/features/Main/Lottery.tsx
  client/src/features/Main/Rush.tsx
  client/src/features/Rush/Casper/CasperCharge.tsx
  client/src/features/Rush/Casper/CasperComfortable.tsx
  client/src/features/Rush/Casper/CasperFar.tsx
  client/src/features/Rush/Casper/CasperFast.tsx
  client/src/features/Rush/Casper/CasperSection.tsx
  client/src/features/Rush/Casper/CasperSmartKey.tsx
  client/src/features/Rush/Casper/CasperWide.tsx
  client/src/features/Rush/Common/FAQ.tsx
  client/src/features/Rush/Common/Intro.tsx
  client/src/features/Rush/Electric/ElectricAdvantage.tsx
  client/src/features/Rush/Electric/ElectricReason.tsx
  client/src/features/Rush/Electric/ElectricSection.tsx
  client/src/features/Rush/Reason/ReasonFirst.tsx
  client/src/features/Rush/Reason/ReasonSecond.tsx
  client/src/features/Rush/Reason/ReasonSection.tsx
  client/src/hooks/useLazyLoading.ts
Labels: feat

#185 [Fix] 어드민 오류 수정
  admin/src/apis/lotteryAPI.ts
  admin/src/components/Suspense/index.tsx
  admin/src/components/TimePicker/index.tsx
  admin/src/constants/common.ts
  admin/src/hooks/useFetch.ts
  admin/src/hooks/useInfiniteFetch.ts
  admin/src/pages/LotteryParticipantList/index.tsx
  admin/src/pages/LotteryWinner/index.tsx
  admin/src/pages/LotteryWinnerList/index.tsx
  admin/src/pages/RushWinnerList/index.tsx
  admin/src/types/lotteryApi.ts
  admin/src/utils/fetchWithTimeout.ts
  admin/src/utils/getTimeDifference.ts
Labels: fix

#188 [Refactor] as const 선언 -> 상수로 수정
  admin/src/constants/common.ts
  admin/src/constants/cookie.ts
  admin/src/constants/rush.ts
  admin/src/types/lottery.ts
  admin/src/types/rush.ts
  client/src/constants/CasperCustom/casper.ts
  client/src/constants/CasperCustom/customStep.tsx
  client/src/constants/PageSections/sections.ts
  client/src/constants/Rush/rushCard.ts
  client/src/constants/cookie.ts
  client/src/features/CasperCustom/CasperCard/CasperCardBackUI.tsx
  client/src/features/CasperCustom/CasperCard/CasperCardFrontUI.tsx
  client/src/features/CasperCustom/CasperCard/CasperFlipCard.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardBack.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardFront.tsx
  client/src/features/CasperCustom/CasperCustomPanel/CasperCustomPanel.tsx
  client/src/features/CasperCustom/CasperCustomPanel/SharedPanel.tsx
  client/src/types/casperCustom.ts
  client/src/types/phoneNumber.ts
  client/src/utils/CasperCustom/getCasperEyesComponent.tsx
  client/src/utils/CasperCustom/getCasperMouthComponent.tsx
  client/src/utils/CasperCustom/getCasperStickerComponent.tsx
Labels: refactor

#190 [Feat] 선착순 예외 처리 및 UX 개선
  client/src/components/Suspense/index.tsx
  client/src/contexts/rushGameContext.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardBack.tsx
  client/src/features/CasperCustom/CasperCard/MyCasperCardFront.tsx
  client/src/features/CasperCustom/CasperCustomPanel/CasperCustomPanel.tsx
  client/src/features/CasperCustom/CasperCustomPanel/EyesPanel.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinish.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinishing.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomForm.tsx
  client/src/features/CasperCustom/CustomProcess/CasperCustomProcess.tsx
  client/src/features/Main/Headline.tsx
  client/src/features/Rush/Common/Headline.tsx
  client/src/features/RushGame/RushGameComponents/RushBar.tsx
  client/src/features/RushGame/RushGameComponents/RushCardComparison.tsx
  client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx
  client/src/features/RushGame/RushGameComponents/RushCardResultDescription.tsx
  client/src/features/RushGame/RushGameComponents/RushCountdown.tsx
  client/src/features/RushGame/RushGameComponents/RushProgressBar.tsx
  client/src/features/RushGame/RushGameComponents/RushResultOptionDisplay.tsx
  client/src/features/RushGame/RushGameComponents/RushShareLink.tsx
  client/src/features/RushGame/RushGameSections/CardOptions.tsx
  client/src/features/RushGame/RushGameSections/Countdown.tsx
  client/src/features/RushGame/RushGameSections/FinalResult.tsx
  client/src/features/RushGame/RushGameSections/SelectedCard.tsx
  client/src/hooks/Contexts/useCasperCustomDispatchContext.ts
  client/src/hooks/Contexts/useCasperCustomStateContext.ts
  client/src/hooks/Contexts/usePhoneNumberDispatchContext.ts
  client/src/hooks/Contexts/usePhoneNumberStateContext.ts
  client/src/hooks/Contexts/useRushGameDispatchContext.ts
  client/src/hooks/Contexts/useRushGameStateContext.ts
  client/src/hooks/RushGame/useFetchRushBalance.ts
  client/src/hooks/RushGame/useFetchRushOptionResult.ts
  client/src/hooks/RushGame/useFetchRushResult.ts
  client/src/hooks/RushGame/useFetchRushUserParticipationStatus.ts
  client/src/hooks/RushGame/useFetchTodayRushEvent.ts
  client/src/hooks/RushGame/useSetGamePhase.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useCountdown.ts
  client/src/hooks/useRushGameContext.ts
  client/src/pages/Lottery/index.tsx
  client/src/pages/RushGame/index.tsx
  client/src/types/rushApi.ts
  client/src/types/rushGame.ts
  client/src/utils/RushGame/getOptionRatio.ts
  client/src/utils/RushGame/getSelectedCardInfo.ts
  client/src/utils/parseIsoDateTime.ts
Labels: fix, feat, refactor

#194 [Fix] 선착순 미참여시 최종 결과 페이지 접근 오류
  client/src/features/RushGame/RushGameSections/FinalResult.tsx
Labels: fix

#193 [Feat] Navigation Block 팝업 커스텀 구현
  client/src/components/NavigationConfirmPopup/index.style.ts
  client/src/components/NavigationConfirmPopup/index.tsx
  client/src/components/PhoneNumberPopUp/index.stories.tsx
  client/src/components/PhoneNumberPopUp/index.tsx
  client/src/features/Rush/Common/Headline.tsx
  client/src/features/RushGame/RushGameSections/FinalResult.tsx
  client/src/features/RushGame/RushGameSections/SelectedCard.tsx
  client/src/hooks/useBlockNavigation.ts
  client/src/hooks/usePhoneNumberPopup.tsx
  client/src/pages/CasperCustom/index.tsx
  client/src/pages/Lottery/index.tsx
  client/src/pages/RushGame/index.tsx
Labels: feat

#195 [Fix] 이벤트 날짜 비교 삭제
  client/src/features/RushGame/RushGameComponents/RushCountdown.tsx
  client/src/features/RushGame/RushGameSections/Countdown.tsx
  client/src/hooks/RushGame/useSetGamePhase.ts
Labels: fix

#197 [Fix] 새로고침 딜레이 추가
  client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx
Labels: fix

#199 [Fix] 응답 완전히 반환 시 요청 보낼 수 있도록 isLoading 추가
  client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx
  client/src/features/RushGame/RushGameSections/SelectedCard.tsx
  client/src/hooks/RushGame/useFetchRushBalance.ts
  client/src/hooks/RushGame/useFetchRushUserParticipationStatus.ts
  client/src/hooks/useFetch.ts
Labels: fix

#202 [Fix] getApplyCount dependency 수정
  client/src/features/CasperCustom/CustomProcess/CasperCustomFinish.tsx
Labels: fix

#203 [Fix] 카드 옵션 선택 시 POST 409 요청 오류
  client/src/features/RushGame/RushGameComponents/RushCardComparison.tsx
Labels: fix

#204 [Chore] console.error 삭제
  admin/src/apis/authAPI.ts
  admin/src/apis/imageAPI.ts
  admin/src/apis/lotteryAPI.ts
  admin/src/apis/rushAPI.ts
  admin/src/hooks/useFetchMultiple.ts
  admin/src/utils/getMsTime.ts
  client/src/apis/authAPI.ts
  client/src/apis/linkAPI.ts
  client/src/apis/lotteryAPI.ts
  client/src/apis/rushAPI.ts
  client/src/apis/totalAPI.ts
  client/src/hooks/useFetch.ts
  client/src/utils/getMsTime.ts
  client/src/utils/saveDomImage.ts
  client/src/utils/writeClipboard.ts
Labels: chore

#207 [Chore] 스티커 랜덤 로직 추가
  client/src/constants/CasperCustom/casper.ts
  client/src/contexts/casperCustomContext.tsx
Labels: chore

#208 [Chore] 스티커 랜덤 로직 추가
  client/src/constants/CasperCustom/casper.ts
  client/src/contexts/casperCustomContext.tsx
Labels: chore
