Repository softeerbootcamp4th/Team7-HybridJGS-FE, pull requests merged in 2024-07, with the labels that each got.

#18 [Feat] Footer 컴포넌트 구현
  client/public/assets/hyundai-logo.svg
  client/src/components/Button/index.stories.ts
  client/src/components/Button/index.tsx
  client/src/components/Footer/index.stories.ts
  client/src/components/Footer/index.tsx
  client/src/router.tsx
  client/tailwind.config.js
Labels: feat

#16 [Feat] CheckBox 컴포넌트 구현
  client/package.json
  client/public/assets/icon/check.svg
  client/src/components/CheckBox/index.stories.tsx
  client/src/components/CheckBox/index.tsx
  client/tailwind.config.js
  client/yarn.lock
Labels: feat

#19 [Feat] Notice 컴포넌트 구현
  client/src/components/Notice/index.stories.ts
  client/src/components/Notice/index.tsx
  client/src/index.css
  client/tailwind.config.js
Labels: feat

#21 [Chore] hyundai sans 폰트 수정
  client/public/fonts/hyundai-sans/HyundaiSansHeadKROTFBold.otf
  client/public/fonts/hyundai-sans/HyundaiSansHeadKROTFLight.otf
  client/public/fonts/hyundai-sans/HyundaiSansHeadKROTFMedium.otf
  client/public/fonts/hyundai-sans/HyundaiSansHeadKROTFRegular.otf
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Bold.woff
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Bold.woff2
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Light.woff
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Light.woff2
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Medium.woff
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Medium.woff2
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Regular.woff
  client/public/fonts/hyundai-sans/HyundaiSansHeadOffice-Regular.woff2
  client/public/fonts/hyundai-sans/HyundaiSansTextKROTFBold.otf
  client/public/fonts/hyundai-sans/HyundaiSansTextKROTFMedium.otf
  client/public/fonts/hyundai-sans/HyundaiSansTextKROTFRegular.otf
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Bold.woff
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Bold.woff2
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Medium.woff
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Medium.woff2
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Regular.woff
  client/public/fonts/hyundai-sans/HyundaiSansTextOffice-Regular.woff2
  client/src/index.css
Labels: chore

#23 [Fix] tsconfig에 alias 선언 형식 추가
  client/tsconfig.app.json
Labels: fix

#22 [Chore] Toggle Storybook docs 추가
  client/src/components/Toggle/index.stories.tsx
Labels: chore

#25 [Feat] Toast 컴포넌트 구현
  client/src/components/Toast/index.stories.tsx
  client/src/components/Toast/index.tsx
  client/src/hooks/useToast.tsx
Labels: feat

#28 [Fix] 전체 텍스트 스타일 수정
  client/public/fonts/hyundai-sans/HyundaiSansHeadKROTFLight.otf
  client/src/components/Notice/index.tsx
  client/tailwind.config.js
Labels: design

#27 [Feat] Input 컴포넌트 구현
  client/src/components/Input/index.stories.tsx
  client/src/components/Input/index.tsx
  client/src/index.css
Labels: feat

#32 [Feat] Keyword 컴포넌트 구현
  client/src/components/Keyword/index.stories.tsx
  client/src/components/Keyword/index.tsx
Labels: feat

#34 [Feat] Category 컴포넌트 구현
  client/src/components/Category/index.stories.tsx
  client/src/components/Category/index.tsx
Labels: feat

#38 [Feat] Scroll 컴포넌트 구현
  client/public/assets/icon/arrow-down.svg
  client/src/components/Scroll/index.stories.tsx
  client/src/components/Scroll/index.tsx
Labels: feat

#31 [Fix] Toggle 디자인 수정사항 반영
  client/src/components/Toggle/index.stories.tsx
  client/src/components/Toggle/index.tsx
Labels: fix

#29 [Feat] Header 컴포넌트 구현
  client/.storybook/preview.tsx
  client/src/components/ButtonHeader/index.stories.tsx
  client/src/components/ButtonHeader/index.style.tsx
  client/src/components/ButtonHeader/index.tsx
  client/src/components/Header/index.stories.tsx
  client/src/components/Header/index.style.tsx
  client/src/components/Header/index.tsx
Labels: feat

#37 [Feat] Button 및 CTAButton 컴포넌트 구현
  client/package.json
  client/public/assets/icon/arrow.svg
  client/public/assets/icon/share.svg
  client/src/components/Button/index.stories.ts
  client/src/components/Button/index.stories.tsx
  client/src/components/Button/index.tsx
  client/src/components/CTAButton/index.stories.tsx
  client/src/components/CTAButton/index.tsx
  client/src/index.css
  client/tailwind.config.js
  client/vite.config.ts
  client/yarn.lock
Labels: feat

#40 [Chore] Admin 초기 세팅
  admin/.eslintrc.cjs
  admin/.gitignore
  admin/.prettierrc
  admin/README.md
  admin/index.html
  admin/package.json
  admin/postcss.config.js
  admin/public/fonts/HyundaiSansHeadKROTFBold.otf
  admin/public/fonts/HyundaiSansHeadKROTFLight.otf
  admin/public/fonts/HyundaiSansHeadKROTFMedium.otf
  admin/public/fonts/HyundaiSansHeadKROTFRegular.otf
  admin/public/fonts/HyundaiSansTextKROTFBold.otf
  admin/public/fonts/HyundaiSansTextKROTFMedium.otf
  admin/public/fonts/HyundaiSansTextKROTFRegular.otf
  admin/public/vite.svg
  admin/src/assets/react.svg
  admin/src/index.css
  admin/src/index.tsx
  admin/src/router.tsx
  admin/src/vite-env.d.ts
  admin/tailwind.config.js
  admin/tsconfig.app.json
  admin/tsconfig.json
  admin/tsconfig.node.json
  admin/vite.config.ts
  admin/yarn.lock
Labels: chore

#42 [Chore] 라우팅 구조 구축
  client/src/components/Layout/index.tsx
  client/src/pages/BotCustom/index.tsx
  client/src/pages/BotCustomResult/index.tsx
  client/src/pages/BotShowCase/index.tsx
  client/src/pages/Lottery/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Rush/index.tsx
  client/src/router.tsx
Labels: chore

#44 [Chore] Layout에 헤더 추가
  client/src/components/Layout/index.tsx
Labels: chore

#53 [Fix] Scroll 기본 스타일 부여
  client/src/components/Scroll/index.tsx
Labels: fix

#55 [Fix] tooltip position prop를 left, center, right로 제한
  client/src/components/Tooltip/index.stories.tsx
  client/src/components/Tooltip/index.tsx
Labels: fix

#56 [Fix] CTA Button 기능 추가
  client/src/components/CTAButton/index.stories.tsx
  client/src/components/CTAButton/index.tsx
  client/src/pages/Main/index.tsx
Labels: feat

#35 [Feat] PopUp 컴포넌트 구현
  client/public/assets/icon/close.svg
  client/src/components/CheckBox/index.stories.tsx
  client/src/components/CheckBox/index.style.tsx
  client/src/components/CheckBox/index.tsx
  client/src/components/Input/index.tsx
  client/src/components/PopUp/index.stories.tsx
  client/src/components/PopUp/index.tsx
  client/src/utils/formatPhoneNumber.ts
Labels: feat

#61 [Fix] 폴더명 대소문자 구별할 수 있게 수정
  client/src/features/Lottery/CustomDesign.tsx
  client/src/features/Lottery/Description.tsx
  client/src/features/Lottery/HeadLamp.tsx
  client/src/features/Lottery/Headline.tsx
  client/src/features/Lottery/Intro.tsx
  client/src/features/Lottery/NewColor.tsx
  client/src/features/Lottery/PixelDesign.tsx
  client/src/features/Lottery/Section.tsx
  client/src/features/Lottery/ShortCut.tsx
  client/src/features/Lottery/SmileBadge.tsx
  client/src/features/Lottery/WheelDesign.tsx
Labels: fix

#62 [Fix] close icon 경로 수정
  client/public/assets/icons/close.svg
  client/src/components/PopUp/index.tsx
Labels: fix

#64 [Fix] 빌드 시 발생한 CTA Button 내부 타입 오류 수정
  client/src/components/CTAButton/index.tsx
  client/tsconfig.app.json
Labels: fix

#66 [Chore] 워크플로우 액션 추가
  .github/workflows/client_pull_request.yml
  .github/workflows/client_push.yml
Labels: chore

#74 [Feat] 헤더 클릭 라우팅 추가 및 수정
  client/src/components/Header/index.tsx
Labels: feat

#68 [Feat] LotteryEvent 컴포넌트 구현 및 임시 데이터 연동
  client/public/assets/main/lottery/prize-1.png
  client/public/assets/main/lottery/prize-2.png
  client/public/assets/main/lottery/prize-3.png
  client/public/assets/main/lottery/prize-4.png
  client/public/assets/main/lottery/prize-5.png
  client/src/components/LotteryEvent/index.stories.tsx
  client/src/components/LotteryEvent/index.tsx
  client/src/constants/Main/lotteryEventData.ts
  client/src/features/Main/Lottery.tsx
Labels: feat

#70 [Feat] RushEvent 컴포넌트 구현
  client/public/assets/main/rush/prize-1.png
  client/public/assets/main/rush/prize-2.png
  client/public/assets/main/rush/prize-3.jpg
  client/public/assets/main/rush/prize-4.jpeg
  client/public/assets/main/rush/prize-5.jpg
  client/public/assets/main/rush/prize-6.jpg
  client/src/components/RushEvent/index.stories.tsx
  client/src/components/RushEvent/index.tsx
  client/src/features/Main/Rush.tsx
  client/src/utils/formatDate.ts
Labels: feat

#75 [Feat] 추첨 페이지 모달 연결
  client/src/components/Input/index.tsx
  client/src/components/PopUp/index.tsx
  client/src/components/Toast/index.tsx
  client/src/features/Lottery/Headline.tsx
  client/src/features/Lottery/ShortCut.tsx
  client/src/hooks/usePopup.tsx
  client/src/pages/Lottery/index.tsx
Labels: feat
